import { Document, Paragraph, TextRun, HeadingLevel, Packer } from 'docx';
import { saveAs } from 'file-saver';

export async function exportNoteToWord(
  title: string,
  content: string,
  aiSummary?: string
) {
  const sections: Paragraph[] = [];

  // Title
  sections.push(
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 400 }
    })
  );

  // AI Summary section (if exists)
  if (aiSummary) {
    sections.push(
      new Paragraph({
        text: "AI Summary",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 }
      })
    );

    aiSummary.split('\n').forEach(line => {
      sections.push(new Paragraph({
        text: line,
        spacing: { after: 100 }
      }));
    });

    sections.push(
      new Paragraph({
        text: "Detailed Notes",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 }
      })
    );
  }

  // Content (preserve line breaks and bullet points)
  content.split('\n').forEach(line => {
    sections.push(new Paragraph({
      text: line,
      spacing: { after: 100 }
    }));
  });

  // Metadata footer
  sections.push(
    new Paragraph({
      text: `Generated by Overlay Platform on ${new Date().toLocaleDateString()}`,
      spacing: { before: 800 }
    })
  );

  const doc = new Document({
    sections: [{ children: sections }]
  });

  const blob = await Packer.toBlob(doc);
  const safeFilename = title.replace(/[^a-z0-9]/gi, '_');
  saveAs(blob, `${safeFilename}.docx`);
}
